

// generate-docx.js
// Node.js class that generates a stylish Word (.docx) document from a payload
// Uses the `docx` package (https://www.npmjs.com/package/docx)
// Usage:
//   npm install docx
//   node generate-docx.js

const fs = require("fs");
const {
  Document,
  Packer,
  Paragraph,
  TextRun,
  Table,
  TableRow,
  TableCell,
  WidthType,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
  Footer,
  PageNumber,
} = require("docx");

/**
 * Class: DocGenerator
 * Generates a DOCX document from a configuration payload.
 * Example:
 *   const gen = new DocGenerator(payload);
 *   await gen.generate("output.docx");
 */
class DocGenerator {
  /**
   * @param {Object} payload - the input payload to render
   * @param {Object} [options] - optional settings
   * @param {string} [options.creator] - document creator
   */
  constructor(payload = {}, options = {}) {
    this.payload = payload;
    this.options = options;
    this.creator = options.creator || "Autogenerated by DocGenerator";
  }

  // Helper: pretty-prints booleans and nulls
  static _prettyBool(v) {
    return v === true ? "Yes" : v === false ? "No" : String(v);
  }

  // Build the document's title paragraph
  _buildTitle() {
    return new Paragraph({
      text: this.payload.displayName || "Configuration Item",
      heading: HeadingLevel.HEADING_1,
      alignment: AlignmentType.START,
      spacing: { after: 200 },
    });
  }

  _buildSubtitle() {
    console.log(typeof this.payload.parameterName);
    console.log(typeof this.payload.parameterValue);

    return new Paragraph({
      children: [
        new TextRun({ text: this.payload.parameterName || "", bold: true }),
      ],
      alignment: AlignmentType.START,
      spacing: { after: 240 },
    });
  }

  _buildBadge() {
    const value = this.payload.parameterValue;
    const valueText =
      value === true ? "ENABLED" : value === false ? "DISABLED" : String(value);
    const valueRun = new TextRun({
      text: valueText,
      bold: true,
      color: value === true ? "006400" : "8B0000",
    });
    return new Paragraph({
      children: [
        new TextRun({ text: "Current value: ", italics: true }),
        valueRun,
      ],
      alignment: AlignmentType.CENTER,
      spacing: { after: 300 },
    });
  }

  _buildDescription() {
    return new Paragraph({
      children: [
        new TextRun({ text: "Description:	", bold: true }),
        new TextRun({ text: this.payload.description || "-" }),
      ],
      spacing: { after: 300 },
    });
  }

  _buildDetailsTable() {
    const rows = [];

    // Header
    rows.push(
      new TableRow({
        children: [
          new TableCell({
            width: { size: 40, type: WidthType.PERCENTAGE },
            margins: { top: 100, bottom: 100, left: 100, right: 100 },
            shading: { fill: "F2F2F2" },
            children: [
              new Paragraph({
                children: [new TextRun({ text: "Property", bold: true })],
              }),
            ],
          }),
          new TableCell({
            width: { size: 60, type: WidthType.PERCENTAGE },
            margins: { top: 100, bottom: 100, left: 100, right: 100 },
            shading: { fill: "F2F2F2" },
            children: [
              new Paragraph({
                children: [new TextRun({ text: "Value", bold: true })],
              }),
            ],
          }),
        ],
      })
    );

    function makeRow(prop, val) {
      return new TableRow({
        children: [
          new TableCell({
            children: [new Paragraph({ text: prop })],
            margins: { top: 100, bottom: 100, left: 100, right: 100 },
          }),
          new TableCell({
            children: [new Paragraph({ text: val })],
            margins: { top: 100, bottom: 100, left: 100, right: 100 },
          }),
        ],
      });
    }

    rows.push(makeRow("Parameter Type", this.payload.parameterType || "-"));
    rows.push(
      makeRow("Is Default", DocGenerator._prettyBool(this.payload.isDefault))
    );
    rows.push(
      makeRow(
        "Default Value",
        DocGenerator._prettyBool(this.payload.defaultValue)
      )
    );
    rows.push(
      makeRow(
        "Is Customer Editable",
        DocGenerator._prettyBool(this.payload.isCustomerEditable)
      )
    );
    rows.push(
      makeRow(
        "Parameter Value",
        DocGenerator._prettyBool(this.payload.parameterValue)
      )
    );

    return new Table({
      rows,
      width: { size: 100, type: WidthType.PERCENTAGE },
      borders: {
        top: { style: BorderStyle.SINGLE, size: 1, color: "BFBFBF" },
        bottom: { style: BorderStyle.SINGLE, size: 1, color: "BFBFBF" },
        left: { style: BorderStyle.SINGLE, size: 1, color: "BFBFBF" },
        right: { style: BorderStyle.SINGLE, size: 1, color: "BFBFBF" },
        insideHorizontal: {
          style: BorderStyle.SINGLE,
          size: 1,
          color: "EDEDED",
        },
        insideVertical: { style: BorderStyle.SINGLE, size: 1, color: "EDEDED" },
      },
      margin: { top: 200, bottom: 200 },
    });
  }

  _buildNote() {
    return new Paragraph({
      children: [
        new TextRun({ text: "Note: ", bold: true }),
        new TextRun({ text: (this.payload.description || "-").slice(0, 400) }),
      ],
      spacing: { before: 300 },
    });
  }


  async generate(filename = "output.docx") {
    const title = this._buildTitle();
    const subtitle = this._buildSubtitle();
    const badge = this._buildBadge();
    const description = this._buildDescription();
    const detailsTable = this._buildDetailsTable();
    const note = this._buildNote();

    const doc = new Document({
      creator: this.creator,
      title: this.payload.displayName || "Configuration Document",
      description:
        this.payload.description || "Generated configuration documentation",
      sections: [
        {
          properties: {},
          footers: {
            default: new Footer({
              children: [
                new Paragraph({
                  alignment: AlignmentType.CENTER,
                  children: [
                    new TextRun({
                      text: `Generated: ${new Date().toLocaleString()}`,
                    }),
                    new TextRun({ text: "  •  " }),
                    new TextRun({ text: "Page " }),
                    PageNumber.CURRENT,
                  ],
                }),
              ],
            }),
          },
          children: [title, subtitle, badge, description, detailsTable, note],
        },
      ],
    });

    const buffer = await Packer.toBuffer(doc);
    fs.writeFileSync(filename, buffer);
    return filename;
  }
}

module.exports = { DocGenerator };

// if (require.main === module) {
//   const examplePayload = {
//     parameterType: "java.lang.Boolean",
//     isDefault: false,
//     displayName: "Audit automatic rejection of email approvals",
//     defaultValue: false,
//     description:
//       "Determines whether your site keeps a record of email approvals that were rejected automatically based on a check of the sender's email address. The audit information includes the email address from which the approval was sent, the name of the approver, the approvable involved, and the content of the message. SAP Ariba representatives can access the information.",
//     parameterName: "Application.Base.EmailApprovalAutoRejectAudit",
//     isCustomerEditable: true,
//     parameterValue: true,
//   };

//   (async () => {
//     try {
//       const gen = new DocGenerator(examplePayload, { creator: "Doc Generator" });
//       const out = await gen.generate("Audit-AutoReject-EmailApprovals.docx");

//       console.log(`Saved ${out}`);
//     } catch (err) {
//       console.error("Failed to generate doc:", err);
//     }
//   })();
// }
