GET http://localhost:4004/odata/v4/generate-document/generate HTTP/1.1

### 
POST  http://localhost:4004/odata/v4/generate-document/getDocumentCreated HTTP/1.1
Content-Type: application/json

{
    "input": "Test Input"
}

###
GET http://localhost:4004/odata/v4/generate-document/getDocumentCreated?params={"parameterName":["Application.Approvable.AllowApprovalOfDeniedApprovable,Application.Approvable.AllowedForExternalApproval,Application.Approvable.ApprovalRequestEscalateWarningPeriod"],"isCustomerEditable":true} HTTP/1.1
Content-Type: application/json

